[2020-04-07 17:11:28,473][Thread-4:2296][task_id:django.request][exception.py:132][ERROR][Internal Server Error: /archives/]
Traceback (most recent call last):
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'bid'
[2020-04-07 21:19:24,786][Thread-10:15460][task_id:django.request][exception.py:132][ERROR][Internal Server Error: /category/]
Traceback (most recent call last):
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\python learning\Ebook_mall\Book\views.py", line 96, in get
    data = search(request, classification=classification)
  File "E:\python learning\Ebook_mall\Book\views.py", line 67, in search
    'categorynum': int(url_prefix.split('/')[2])}
ValueError: invalid literal for int() with base 10: ''
[2020-04-07 21:22:59,142][Thread-28:9520][task_id:django.request][exception.py:132][ERROR][Internal Server Error: /tag/]
Traceback (most recent call last):
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\python learning\Ebook_mall\Book\views.py", line 106, in get
    data = search(request, ntag=ntag)
  File "E:\python learning\Ebook_mall\Book\views.py", line 70, in search
    'tagnum': int(url_prefix.split('/')[2])}
ValueError: invalid literal for int() with base 10: ''
[2020-04-07 21:27:02,457][Thread-1:12492][task_id:django.request][exception.py:132][ERROR][Internal Server Error: /tag/]
Traceback (most recent call last):
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\python learning\Ebook_mall\Book\views.py", line 107, in get
    data = search(request, ntag=ntag)
  File "E:\python learning\Ebook_mall\Book\views.py", line 71, in search
    'tagnum': int(url_prefix.split('/')[2])}
ValueError: invalid literal for int() with base 10: ''
[2020-04-07 21:28:08,237][Thread-1:1776][task_id:django.request][exception.py:132][ERROR][Internal Server Error: /tag/]
Traceback (most recent call last):
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\python learning\Ebook_mall\Book\views.py", line 110, in get
    data = search(request, ntag=ntag)
  File "E:\python learning\Ebook_mall\Book\views.py", line 74, in search
    'tagnum': int(url_prefix.split('/')[2])}
ValueError: invalid literal for int() with base 10: ''
[2020-04-07 23:19:30,382][Thread-3:5644][task_id:django.request][exception.py:132][ERROR][Internal Server Error: /category/]
Traceback (most recent call last):
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\python learning\Ebook_mall\Book\views.py", line 101, in get
    return render(request, 'bookshow_searchshow.html', data)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 135, in find_template
    template = loader.get_template(
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 43, in get_template
    return Template(
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 827, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 486, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 484, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 699, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '-1.book_tag' from 'book.-1.book_tag'
[2020-04-07 23:21:20,065][Thread-3:16744][task_id:django.request][exception.py:132][ERROR][Internal Server Error: /category/]
Traceback (most recent call last):
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\python learning\Ebook_mall\Book\views.py", line 102, in get
    return render(request, 'bookshow_searchshow.html', data)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 135, in find_template
    template = loader.get_template(
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 43, in get_template
    return Template(
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 827, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 486, in parse
    raise self.error(token, e)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 484, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\wzdlu\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 699, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '-1.book_tag' from 'book.-1.book_tag'
